name: Orebfuscator
main: lishid.orebfuscator.Orebfuscator
version: 1.0.0
author: lishid
description: >
  This plugin obfuscates data that is sent to players to prevent x-ray.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
      /<command> engine <1|2> - Set engine mode to 1 or 2
      /<command> reload - Reload from config file
      /<command> enable
      /<command> disable

permissions:
  Orebfuscator.admin:
    description: Orebfuscator commands
    default: op